### PR TITLE
Adjust league (Fixes #619, #621 & #623)

### LINKED ISSUE #619: PlayerOrTeamName is Null
League.GetLeaguePositionsAsync

image

### LINKED ISSUE #621: Update league endpoint
Add
- `/lol/league/v4/entries/by-summoner/{encryptedSummonerId}`
- `/lol/league/v4/entries/{queue}/{tier}/{division}`
- `/lol/league/v4/grandmasterleagues/by-queue/{queue}`
- `/lol/league/v4/leagues/{leagueId}`

Remove:

- `GetLeaguePositionsAsync`

Ref:
https://developer.riotgames.com/api-methods/#league-v4/GET_getLeagueById

### LINKED ISSUE #623: GetChallengerLeagueAsync has incorrect modal
When im calling `await api.League.GetChallengerLeagueAsync(Region.Euw, Queue.RankedSolo5x5);` the enties modal looks like this: 

image

As you can see `leagueName` is null for all entries. I think this is because the Riot api defines this property as `summonerName` and also `summonerId`, which is missing. Changing the region or queue doen't change the result.

I think that this might be a bug since the `LeaguePosition` model doesn't corresponds with the RiotApi model.

### PR DESCRIPTION
**Pull request by kirides**
Should close #619, fix #621 and fix #623

- Removed GetLeagePositionsAsync
- Added four new methods for the endpoints defined in #621
- ~~fixed IServiceCollectionExtensions for AspNetCore~~
- TierConverter now uses Enum.TryParse(string, bool ignoreCase, out enum)
- Base-Classed LeagueEntry (LeaguePosition replacement) with LeagueItem. (Returned from LeagueList-returning endpoints

### CODE REVIEW

File: RiotSharp.AspNetCore/IServiceCollectionExtension.cs [hunk 1]
```diff
@@ -33,6 +33,8 @@ public static IServiceCollection AddRiotSharp(this IServiceCollection serviceCol
             {
                 var rateLimitedRequester = new RateLimitedRequester(riotSharpOptions.RiotApi.ApiKey,
                     riotSharpOptions.RiotApi.RateLimits);
+                var nonLimitingRequester = new Requester(riotSharpOptions.RiotApi.ApiKey);
```
Comment (BenFradet) [inline RiotSharp.AspNetCore/IServiceCollectionExtension.cs]: why do you need it?

**Review by BenFradet — COMMENTED** [review]
LGTM, I just have one q :+1:

File: RiotSharp.AspNetCore/IServiceCollectionExtension.cs (hunk 1 above)
Comment (kirides) [reply RiotSharp.AspNetCore/IServiceCollectionExtension.cs]: Someone added the status endpoint to the API, which lead to the API taking another rate limiter in it's constructor.

IDK if its really necessary, but if the status API is not limited, reusing the rate limited requester would lead to rate limits potentially being fired without hitting a limited endpoint.

Comment (JanOuborny) [reply RiotSharp.AspNetCore/IServiceCollectionExtension.cs]: The problem here is: Right now every requester creates his own `HttpClient` instance. However, the `HttpClient` is threadsafe and designed for concurrent requests, therefore we should reuse the same instance for every requester.  When I migrated the status API, I intentionally left the build error there to fix it properly in a later commit.

Comment (kirides) [reply RiotSharp.AspNetCore/IServiceCollectionExtension.cs]: @JanOuborny Alright, removed that part from the PR :)

**Comment by JanOuborny** [comment]
Looks good 👍 
Just a little thing: Can you add the supported values disclaimer [here](https://github.com/BenFradet/RiotSharp/blob/4c721e512debb8a4bd45b35ba00fef99528618e4/RiotSharp/Endpoints/Interfaces/ILeagueEndpoint.cs#L17)?

**Comment by kirides** [comment]
Done

**Comment by BenFradet** [comment]
are we good to go here @JanOuborny ?

**Review by JanOuborny — APPROVED** [review]
I think so @BenFradet
